version: '3.8'

services:
  app:
    build: .
    container_name: megasena-app
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "${DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
